---
title: CYNK Studios
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: CYNK Studios
description: CYNK Studios is an experimental art space in Ypsilanti, MI
permalink: "/:title/"
lang: en
excerpt_separator: |2+



date_format: "%B %d, %Y"
future: true
show_excerpts: false
show_frame: true
show_sidebar: false
minimal: false
navigation:
- file: index.md
- file: pastshows.md
- file: upcoming.md
- file: about.md
external:
- title: Mail
  icon: envelope
  url: mailto:hi@cynkypsi.com
- title: Instagram
  icon: instagram
  url: https://www.instagram.com/cynkypsi
comments: 
plugins:
- jekyll-feed
